services:
  origin-latency-probe:
    build: .
    image: ghcr.io/jirong0214/origin-latency-probe:latest
    container_name: origin-latency-probe
    restart: unless-stopped
    environment:
      PROBE_APP_NAME: p.zshio.de
      PROBE_PORT: "12071"
    ports:
      - "127.0.0.1:12071:12071"

  origin-latency-ui:
    build: ./frontend
    image: ghcr.io/jirong0214/origin-latency-probe-ui:latest
    container_name: origin-latency-ui
    restart: unless-stopped
    depends_on:
      - origin-latency-probe
    ports:
      - "127.0.0.1:12072:80"
